name: Type labeler

on:
  pull_request:
    types:
      - opened

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: add âœ¨ Feat label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'feat:') }}
        with:
          labels: âœ¨ Feat

      - name: add ğŸ Bug label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'fix:') }}
        with:
          labels: ğŸ Bug

      - name: add ğŸ”¨ Refactor label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'refactor:') }}
        with:
          labels: ğŸ”¨ Refactor

      - name: add ğŸ¨ Style label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'style:') }}
        with:
          labels: ğŸ¨ Style

      - name: add âš™ Setting label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'chore:') }}
        with:
          labels: âš™ Setting

      - name: add âœ… Test label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'test:') }}
        with:
          labels: âœ… Test

      - name: add ğŸ“ Docs label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'docs:') }}
        with:
          labels: ğŸ“ Docs
